### ISSUE TITLE
Make it a http://silab-bonn.github.io page

### ISSUE THREAD

**Issue by themperek** [SiLab-Bonn/silab_thesis_topics#1]
It is rather easy to use https://pages.github.com/ to host a website using [jegyll](https://help.github.com/en/articles/using-jekyll-as-a-static-site-generator-with-github-pages)

**Comment by leloup314** [comment]
Looks good. I will try to do this in the next weeks.

**Comment by leloup314** [comment]
It's done. See [here](https://silab-bonn.github.io/)
